version: '2'
services:
  flask1:
    build: ./flask
    ports:
     - "7496"
     - "7373"
     - "5000:5000"
    volumes:
     - ./flask/code:/code
    links:
     - redis
     - salt
    depends_on:
     - redis
     - salt
    hostname: flask1
    container_name: flask1
    tty: true
  flask2:
    build: ./flask
    ports:
     - "7496"
     - "7373"
     - "5001:5000"
    volumes:
     - ./flask/code:/code
    links:
     - redis
     - salt
    depends_on:
     - redis
     - salt
    hostname: flask2
    container_name: flask2
    tty: true
  redis:
    build: ./redis
    ports:
     - "7496"
     - "7373"
     - "6379:6379"
    links:
     - salt
    depends_on:
     - salt
    hostname: redis
    container_name: redis
    tty: true
  varnish:
    build: ./varnish
    ports:
     - "7496"
     - "7373"
     - "5007:80"
    links:
     - haproxy
     - salt
    depends_on:
     - haproxy
     - salt
    hostname: varnish
    container_name: varnish
    tty: true
  haproxy:
    build: ./haproxy
    ports:
     - "7496"
     - "7373"
     - "5008:80"
    links:
     - flask1
     - salt
    depends_on:
     - flask1
     - salt
    hostname: haproxy
    container_name: haproxy
    tty: true
  salt:
    build: ./salt
    ports:
     - "7496"
     - "7373"
     - "4505:4505"
     - "4506:4506"
    hostname: salt
    container_name: salt
    tty: true
